# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github Blog 
url: http://mutex86.github.io
feed: /atom.xml
author_info: <a href="http://mutex86.github.io/">mutex86</a>

myblog:
  gavatar: images/2.jpg
  gpname: mutex86
  linkedin: http://blog.csdn.net/mutex86
  github: https://github.com/mutex86
  email: mailto:gningh@gmail.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
